name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set IMAGE_TAG as Git SHA
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t muhammadkaif/flask-deployedapp:${IMAGE_TAG} .
          docker tag muhammadkaif/flask-deployedapp:${IMAGE_TAG} muhammadkaif/flask-deployedapp:latest
          docker push muhammadkaif/flask-deployedapp:${IMAGE_TAG}
          docker push muhammadkaif/flask-deployedapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1

      - name: Deploy to AWS S3
        run: |
          zip -r deploy.zip . -x '*.git*'
          aws s3 cp deploy.zip s3://flask-cicd-deployments/deploy.zip

      - name: Trigger AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name FlaskApp \
            --deployment-group-name FlaskApp-Group \
            --s3-location bucket=flask-cicd-deployments,key=deploy.zip,bundleType=zip
